---
title: "Draft Quarto document"
author: "Your Name"
format: html
editor_options: 
  chunk_output_type: console
---

## Header 1

```{r setup}
library(tidyverse)
library(targets)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results: Basic stats table

```{r}
tar_read(table_descriptive_stats) |>
  knitr::kable(
    caption = "The mean and standard deviation of metabolites in the lipidomics dataset."
  )
```

## Results: Distribution plot

```{r}
tar_read(plot_distributions) |>
  print()
```

## Figure of model estimates

```{r}
model_results <- tar_read(model_results)

model_results |>
  filter(
    term == "value",
    std.error <= 2,
    estimate <= 5,
  ) |>
  select(metabolite, model, estimate, std.error) |>
  ggplot(aes(
    x = estimate,
    y = metabolite,
    xmin = estimate - std.error,
    xmax = estimate + std.error
  )) +
  geom_pointrange() +
  geom_vline(xintercept = 1, linetype = "dashed") +
  facet_grid(cols = vars(model)) +
  theme_minimal()
```

## Appendix

```{r}
tar_read(model_results) |>
  knitr::kable(
    caption = "All model results from all metabolites."
  )
```
